import type { Metadata } from "next";
import { Alegreya, Tilt_Warp} from "next/font/google";

import "./globals.css";

const alegreyaSerif = Alegreya({
  variable: "--font-alegreya-serif",
  subsets: ["latin"],
});

const tiltWarp = Tilt_Warp({
  variable: "--font-tilt_warp-sans-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alegreyaSerif.variable} ${tiltWarp.variable} antialiased`}
      >
        <header id="nav-area">
            <section id="nav-content">
                <a href="index.html" ></a>
                <button id="hamburger" ></button>
                <h1 > Nathan H</h1>             
                <nav >
                    <div >
                        <a href="index.html">Home</a>

                        <a href="codeProjects.html">Code Projects</a>
                        <a href="artProjects.html">Art Projects</a>
                        <a href="misc.html">Other Work</a>
                        <a href="contact.html">Contact</a>
                        <a href="cv.html">CV</a>
                    </div>
                </nav>
            </section>
        </header>
        {children}

        <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center">
        <section >
                <div >
                    <a href="index.html">Home</a>
                    <a href="codeProjects.html">Code Projects</a>
                    <a href="artProjects.html">Art Projects</a>
                    <a href="misc.html">Other Work</a>
                    <a href="contact.html" >Contact</a>
                    <a href="cv.html">CV</a>

                </div>
                <div >
                    <div id="social" >
                        <a href="https://www.linkedin.com/in/nathan-heaton-478541300/" target="_blank">
                            
                        </a>
                    </div>

                    <div id="social" >
                        <a href="https://github.com/NathanHeaton" target="_blank">
                            
                        </a>
                    </div>
                </div>
                <div >
                  
                    <p>Made by Nathan Heaton 2024</p>
                </div>
            </section>
        </footer>
      </body>
    </html>
  );
}
